<a href="https://colab.research.google.com/github/rabikkk/Autonomous-Flight-Controller/blob/master/numpy_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
my_matrix = np.matrix(np.random.rand(5, 3), dtype=np.float32) 
for i in my_matrix:
  print(i)

[[0.13002858 0.01936696 0.6788355 ]]
[[0.21162811 0.26554665 0.49157315]]
[[0.05336254 0.5741176  0.14672858]]
[[0.5893055  0.69975835 0.10233443]]
[[0.41405597 0.69440013 0.41417927]]


In [ ]:
import numpy as np
import random 
my_matrix= np.zeros(shape=(5,3))
for i in range(5):
  for k in range(3):
          X = np.append(X, [[i, j]], axis=0)
    .np.ndarray(random.randrange(-1, 2))

In [14]:
import numpy 
import random 
my_matrix= numpy.empty([5, 3], dtype=float)
for i in range(5):
  for k in range(3):
         my_matrix= numpy.append (my_matrix, [random.uniform(-5, 5)],axis=None)
for i in my_matrix:
  print(i)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]


In [22]:
import numpy 
my_matrix=numpy.random.uniform(-5, 5, size=(5, 3))
for i in my_matrix:
  print(i)

[-1.21232561  2.18509724 -3.70767352]
[ 2.08126616  4.940549   -1.15684118]
[-2.44924264  2.8074404  -4.19907809]
[ 1.30589439  4.2197777  -4.89840765]
[-2.14123859 -1.35758125 -0.92336471]
